# Generated by Django 3.0.5 on 2023-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('General doctort', 'General doctor'), ('Cardiologist', 'Cardiologist'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Dermatologist', 'Dermatologist'), ('ophthalmologist', 'ophthalmologist'), ('Midwife', 'Midwife')], default='General doctor', max_length=50),
        ),
    ]
